name: DLPytorchCVENV
channels:
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - anyio=4.10.0=py311haa95532_0
  - aom=3.12.1=h00a0c3c_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py311h02ab6af_0
  - asttokens=3.0.0=py311haa95532_0
  - async-lru=2.0.5=py311haa95532_0
  - attrs=25.4.0=py311haa95532_2
  - babel=2.17.0=py311haa95532_0
  - beautifulsoup4=4.14.2=py311haa95532_0
  - blas=1.0=mkl
  - bleach=6.3.0=py311haa95532_0
  - bottleneck=1.4.2=py311h540bb41_1
  - brotlicffi=1.1.0.0=py311h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2025.11.12=py311haa95532_0
  - cffi=2.0.0=py311h02ab6af_1
  - charset-normalizer=3.4.4=py311haa95532_0
  - colorama=0.4.6=py311haa95532_0
  - comm=0.2.3=py311haa95532_0
  - contourpy=1.3.3=py311h214f63a_0
  - cuda-cccl=13.0.85=h5221881_1
  - cuda-cccl_win-64=13.0.85=hc667259_1
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=13.0.85=h17533db_0
  - cuda-opencl-dev=13.0.85=hde976d8_0
  - cuda-profiler-api=13.0.85=h5221881_0
  - cuda-runtime=12.1.0=0
  - cuda-version=13.0=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.16=py311h885b0b7_1
  - decorator=5.2.1=py311haa95532_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=2.2.1=py311haa95532_0
  - expat=2.7.3=h9214b88_0
  - filelock=3.20.0=py311haa95532_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.60.1=py311h02ab6af_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - giflib=5.2.2=h7edc060_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py311h827c3e9_0
  - graphite2=1.3.14=hd77b12b_1
  - h11=0.16.0=py311haa95532_1
  - harfbuzz=10.2.0=he2f9f60_1
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py311haa95532_0
  - httpx=0.28.1=py311haa95532_1
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.11=py311haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.31.0=py311h4442805_0
  - ipython=9.7.0=py311haa95532_0
  - ipython_pygments_lexers=1.1.1=py311haa95532_0
  - jedi=0.19.2=py311haa95532_0
  - jinja2=3.1.6=py311haa95532_0
  - joblib=1.5.2=py311haa95532_0
  - jpeg=9f=ha349fce_0
  - json5=0.12.1=py311haa95532_0
  - jsonschema=4.25.0=py311haa95532_1
  - jsonschema-specifications=2025.9.1=py311haa95532_0
  - jupyter-lsp=2.2.5=py311haa95532_0
  - jupyter_client=8.6.3=py311haa95532_1
  - jupyter_core=5.8.1=py311haa95532_0
  - jupyter_events=0.12.0=py311haa95532_0
  - jupyter_server=2.16.0=py311haa95532_0
  - jupyter_server_terminals=0.5.3=py311haa95532_0
  - jupyterlab=4.4.7=py311haa95532_0
  - jupyterlab_pygments=0.3.0=py311haa95532_0
  - jupyterlab_server=2.28.0=py311haa95532_0
  - khronos-opencl-icd-loader=2025.07.22=h79b28c9_0
  - kiwisolver=1.4.9=py311h03f52e7_0
  - lcms2=2.17=h3732fa5_0
  - lerc=4.0.0=h5da7b33_0
  - libavif=1.3.0=h5bd13ec_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.4.0.35=h86a452a_1
  - libcurand-dev=10.4.0.35=hde976d8_1
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libiconv=1.16=h2bbff1b_3
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libkrb5=1.21.3=h885b0b7_4
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libsodium=1.0.20=h83e8143_0
  - libtiff=4.7.1=h3a18249_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.6.0=h55ef9bb_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py311h827c3e9_0
  - matplotlib=3.10.6=py311haa95532_1
  - matplotlib-base=3.10.6=py311h43afe63_1
  - matplotlib-inline=0.2.1=py311haa95532_0
  - mistune=3.1.2=py311haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h827c3e9_2
  - mkl_fft=1.3.11=py311h827c3e9_0
  - mkl_random=1.2.8=py311hea22821_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py311haa95532_0
  - nbclient=0.10.2=py311haa95532_0
  - nbconvert-core=7.16.6=py311haa95532_0
  - nbformat=5.10.4=py311haa95532_0
  - nest-asyncio=1.6.0=py311haa95532_0
  - networkx=3.5=py311haa95532_0
  - notebook-shim=0.2.4=py311haa95532_0
  - numexpr=2.11.0=py311hdb065b2_0
  - opencl-headers=2025.07.22=h885b0b7_0
  - openssl=3.0.18=h543e019_0
  - overrides=7.7.0=py311haa95532_0
  - packaging=25.0=py311haa95532_1
  - pandas=2.3.3=py311h42c1672_1
  - pandocfilters=1.5.1=py311haa95532_0
  - parso=0.8.5=py311haa95532_0
  - pcre2=10.46=h5740b90_0
  - pillow=12.0.0=py311h4212202_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.5.0=py311haa95532_0
  - prometheus_client=0.21.1=py311haa95532_0
  - prompt-toolkit=3.0.52=py311haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py311h02ab6af_1
  - pure_eval=0.2.3=py311haa95532_0
  - pycparser=2.23=py311haa95532_0
  - pygments=2.19.2=py311haa95532_0
  - pyparsing=3.2.5=py311haa95532_0
  - pyqt=6.7.1=py311h378bd72_2
  - pyqt6-sip=13.9.1=py311h02ab6af_2
  - pysocks=1.7.1=py311haa95532_1
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python-fastjsonschema=2.21.2=py311haa95532_0
  - python-json-logger=3.2.1=py311haa95532_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytorch=2.5.1=py3.11_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=py311haa95532_0
  - pywin32=311=py311h885b0b7_0
  - pywinpty=2.0.15=py311h72d21ff_0
  - pyyaml=6.0.3=py311hb9a58be_0
  - pyzmq=27.1.0=py311h7149c55_1
  - qtbase=6.7.3=hd088775_4
  - qtdeclarative=6.7.3=h885b0b7_1
  - qtsvg=6.7.3=h9d4b640_1
  - qttools=6.7.3=hcb596f7_1
  - qtwebchannel=6.7.3=h885b0b7_1
  - qtwebsockets=6.7.3=h885b0b7_1
  - referencing=0.37.0=py311haa95532_0
  - requests=2.32.5=py311haa95532_1
  - rfc3339-validator=0.1.4=py311haa95532_0
  - rfc3986-validator=0.1.1=py311haa95532_0
  - rpds-py=0.28.0=py311h114bc41_0
  - scikit-learn=1.7.2=py311h9296b3f_0
  - scipy=1.16.0=py311h242c13b_0
  - seaborn=0.13.2=py311haa95532_3
  - send2trash=1.8.2=py311haa95532_1
  - setuptools=72.1.0=py311haa95532_0
  - sip=6.10.0=py311h5da7b33_0
  - six=1.17.0=py311haa95532_0
  - sniffio=1.3.1=py311haa95532_0
  - soupsieve=2.5=py311haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=py311haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - terminado=0.18.1=py311haa95532_0
  - threadpoolctl=3.5.0=py311h746a85d_0
  - tinycss2=1.4.0=py311haa95532_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py311h827c3e9_0
  - traitlets=5.14.3=py311haa95532_0
  - typing-extensions=4.15.0=py311haa95532_0
  - typing_extensions=4.15.0=py311haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py311haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py311haa95532_0
  - webencodings=0.5.1=py311haa95532_1
  - websocket-client=1.8.0=py311haa95532_0
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_1
  - winpty=0.4.3=4
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - click==8.3.1
      - coloredlogs==15.0.1
      - einops==0.8.1
      - fastapi==0.122.0
      - flatbuffers==25.9.23
      - fsspec==2025.10.0
      - humanfriendly==10.0
      - ml-dtypes==0.5.4
      - numpy==2.2.6
      - onnx==1.19.1
      - onnxruntime==1.23.2
      - onnxruntime-gpu==1.23.2
      - onnxslim==0.1.77
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - polars==1.35.2
      - polars-runtime-32==1.35.2
      - protobuf==6.33.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyreadline3==3.5.4
      - python-multipart==0.0.20
      - simsimd==6.5.3
      - starlette==0.50.0
      - stringzilla==4.3.0
      - sympy==1.13.1
      - thop==0.1.1-2209072238
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - typing-inspection==0.4.2
      - ultralytics==8.3.233
      - ultralytics-thop==2.0.18
      - uvicorn==0.38.0
